#!/usr/bin/env bash
set -e
. "$VMUXCLI_WORKDIR/config.shlib"
. "$VMUXCLI_WORKDIR/common"

get_detach_key(){
    if [[ "$1" =~ vmux-raspi* ]]
    then
        echo ^q;
    else
        echo ^\\;
    fi

}

create_or_attach() {
	read_config
	server_file="$VMUX_TMP_PATH/$VMUX_SESSION_PREFIX$1"
	session_name="$VMUX_SESSION_PREFIX$1"

    detach_key=$(get_detach_key "$session_name")

	get_all_session
	if [[ ! "${VMUX_SESSIONS[@]}" =~ "$1" ]]; then
		ensure_nvim_socket "$server_file"
	fi
	VMUX_SERVER_FILE=$server_file abduco -e "$detach_key" \
		-"$2" "$session_name" nvim --cmd "let g:vmux_active_session = 1" \
		--cmd "let g:vmux_server_addr = serverstart('$server_file')" \
		--cmd "let g:vmux_session_name = '$1'"
}

create_or_attach "$@"
