#!/usr/bin/env bash
set -e
. $VMUXCLI_WORKDIR/common

_vmux_completions(){
    if [ "${#COMP_WORDS[@]}" != "2" ]; then
        return
    fi
    get_all_session
    local vmux_session_words=$(echo ${VMUX_SESSIONS[@]})
    local suggestions=($(compgen -W "$vmux_session_words" -- "${COMP_WORDS[1]}"))
    if [ "${#suggestions[@]}" > 0 ]; then
        COMPREPLY=("${suggestions[@]}")
    fi
}

complete -F _vmux_completions vmux
