#!/usr/bin/env bash
set -e
. "$VMUXCLI_WORKDIR/config.shlib"
. "$VMUXCLI_WORKDIR/common"

create_or_attach(){
    read_config
    server_file="$VMUX_TMP_PATH/$VMUX_SESSION_PREFIX$1"
    session_name="$VMUX_SESSION_PREFIX$1"
    ensure_nvim_socket $server_file
    abduco -e "$VMUX_DETACH_KEY" \
        -A "$session_name" nvim --cmd "let g:vmux_active_session = 1" \
        --cmd "let g:vmux_server_addr = serverstart('$server_file')"
}

create_or_attach $1
